



CREATE TABLE CIDADE
(
	COD_CIDADE	INT IDENTITY	NOT NULL
	,NOME		VARCHAR(45)		NOT NULL
	,ESTADO		VARCHAR(45)		NOT NULL
	CONSTRAINT PK_COD_CIDADE PRIMARY KEY (COD_CIDADE)
)
GO

CREATE TABLE FORNECEDOR
(
	COD_FORN		INT IDENTITY	NOT NULL
	,NOME			CHAR(30)		NOT NULL
	,CNPJ			FLOAT(45)		NOT NULL
	,ENDEREÇO		VARCHAR(60)		NULL
	,TEL1			VARCHAR(60)		NOT NULL
	,TEL2			VARCHAR(12)		NULL
	,EMAIL			VARCHAR(40)		NOT NULL
	,COD_CIDADE		INT				NOT NULL
	CONSTRAINT PK_COD_FORN PRIMARY KEY (COD_FORN)
)	
GO

CREATE TABLE CLIENTE
(
	CPF_CLI			INT IDENTITY	NOT NULL
	,NOME			CHAR(15)		NOT NULL
	,SOBRENOME		CHAR(30)		NOT NULL
	,NOME_MAE		CHAR(45)		NULL
	,DATA_NASC		DATE			NOT NULL
	,ENDEREÇO		VARCHAR(60)		NOT NULL
	,TELEFONE		VARCHAR (15)	NOT NULL
	,RG				VARCHAR(15)		NOT NULL
	,COD_CID		INT				NOT NULL
	,COD_VEND_COND	INT				NOT NULL
	CONSTRAINT PK_CPF_CLI PRIMARY KEY (CPF_CLI)

)
GO

CREATE TABLE PRODUTOS
(
	COD_PROD		INT IDENTITY	NOT NULL
	,NOME			VARCHAR(45)		NOT NULL
	,PREÇO			DECIMAL(7,2)	NOT NULL
	,COD_DETALHES	INT				NOT NULL
	CONSTRAINT PK_COD_PROD PRIMARY KEY (COD_PROD)

)
GO

CREATE TABLE DETALHES
(
	COD_DETALHES	INT IDENTITY	NOT NULL
	,TAMANHO		VARCHAR(45)		NOT NULL
	,COR			CHAR(15)		NOT NULL
	,QUANT			INT				NOT NULL
	,COD_PROD		INT				NOT NULL
	CONSTRAINT PK_COD_DETALHES PRIMARY KEY (COD_DETALHES)

)
GO

CREATE TABLE CAIXA
(
	COD_CAIXA			INT IDENTITY	NOT NULL
	,PAG_DOS_CLIENTES	INT				NOT NULL
	,VALOR_PAG			DECIMAL(7,2)	NOT NULL
	,DATA_PAG			DATETIME		NOT NULL
	,VENDAS				INT				NOT NULL
	,FORM_PAG			INT				NOT NULL
	CONSTRAINT PK_COD_CAIXA PRIMARY KEY (COD_CAIXA)

)
GO








